import { jsPDF } from "jspdf";
import autoTable from "jspdf-autotable";

export const generatePDFReport = (patientName, data) => {
  const doc = new jsPDF();
  const timestamp = new Date().toLocaleString();
  const reportId = data.id || `REP-${Math.random().toString(36).substr(2, 9).toUpperCase()}`;
  
  // ==========================================
  // PAGE 1: COVER PAGE
  // ==========================================
  
  // Background Graphic Accent (Sidebar Strip)
  doc.setFillColor(225, 29, 72); // rose-600
  doc.rect(0, 0, 15, 297, 'F');

  // Sidebar Accent Line
  doc.setFillColor(15, 23, 42); // slate-900
  doc.rect(15, 0, 3, 297, 'F');
  
  // Application Logo (Abstract Vector Shield/Heart representation)
  // Outer circle
  doc.setDrawColor(225, 29, 72);
  doc.setLineWidth(1.5);
  doc.circle(60, 50, 15, 'S');
  // Inner heart cross
  doc.setFillColor(225, 29, 72);
  doc.rect(58, 41, 4, 18, 'F');
  doc.rect(51, 48, 18, 4, 'F');
  
  // App Title
  doc.setFont("helvetica", "bold");
  doc.setFontSize(26);
  doc.setTextColor(15, 23, 42); // slate-900
  doc.text("CardioSense AI", 85, 48);
  
  doc.setFont("helvetica", "normal");
  doc.setFontSize(10);
  doc.setTextColor(100, 116, 139); // slate-400
  doc.text("SMART PREVENTIVE CARDIOLOGY NETWORK", 85, 54);
  
  // Main Report Title Banner
  doc.setFillColor(244, 245, 247);
  doc.rect(30, 90, 160, 40, 'F');
  doc.setDrawColor(226, 232, 240);
  doc.setLineWidth(0.5);
  doc.rect(30, 90, 160, 40, 'S');
  
  doc.setFont("helvetica", "bold");
  doc.setFontSize(16);
  doc.setTextColor(225, 29, 72);
  doc.text("HEART HEALTH ASSESSMENT REPORT", 38, 106);
  
  doc.setFont("helvetica", "normal");
  doc.setFontSize(11);
  doc.setTextColor(71, 85, 105);
  doc.text("Clinical Classification & Biomarker Summary Analysis", 38, 118);
  
  // Patient details card
  doc.setFont("helvetica", "bold");
  doc.setFontSize(13);
  doc.setTextColor(15, 23, 42);
  doc.text("PATIENT INFORMATION LOG", 30, 160);
  
  doc.setDrawColor(226, 232, 240);
  doc.line(30, 164, 190, 164);
  
  doc.setFont("helvetica", "bold");
  doc.setFontSize(10);
  doc.setTextColor(100, 116, 139);
  
  doc.text("PATIENT NAME:", 30, 176);
  doc.text("REPORT ID:", 30, 186);
  doc.text("GENERATED DATE:", 30, 196);
  doc.text("RISK LEVEL:", 30, 206);
  doc.text("HEALTH SCORE:", 30, 216);

  doc.setFont("helvetica", "bold");
  doc.setTextColor(15, 23, 42);
  doc.text(patientName ? patientName.toUpperCase() : "GUEST PATIENT", 75, 176);
  doc.text(reportId, 75, 186);
  doc.text(timestamp, 75, 196);
  
  // Color code risk level
  const rL = data.riskLevel.toUpperCase();
  if (rL === "HIGH") {
    doc.setTextColor(225, 29, 72);
  } else if (rL === "MEDIUM") {
    doc.setTextColor(245, 158, 11);
  } else {
    doc.setTextColor(16, 185, 129);
  }
  doc.text(`${rL} RISK (${data.riskPercentage}%)`, 75, 206);
  
  doc.setTextColor(15, 23, 42);
  doc.text(`${data.healthScore} / 100`, 75, 216);
  
  // Cover Page Footer info
  doc.setFont("helvetica", "normal");
  doc.setFontSize(8);
  doc.setTextColor(148, 163, 184);
  doc.text("Generated by Heart Health Risk Assessment Tool", 30, 265);
  doc.text("Confidential Medical Information • Scale 1 of 2", 30, 271);
  
  // ==========================================
  // PAGE 2: CLINICAL DETAILS
  // ==========================================
  doc.addPage();
  
  // Reset Sidebar Accent on Page 2
  doc.setFillColor(225, 29, 72);
  doc.rect(0, 0, 8, 297, 'F');
  
  // Header on Page 2
  doc.setFont("helvetica", "bold");
  doc.setFontSize(14);
  doc.setTextColor(15, 23, 42);
  doc.text("Clinical Bio-Markers & Assessment", 18, 20);
  
  doc.setFont("helvetica", "normal");
  doc.setFontSize(9);
  doc.setTextColor(100, 116, 139);
  doc.text(`Patient ID: ${data.id?.slice(-6) || 'Guest'}  |  Assessed: ${data.date || timestamp}`, 18, 25);
  
  // Biomarkers table
  const clinicalRows = [];
  const clinicalInputs = data.inputs || {};

  // Standardize the values to human-readable strings
  clinicalRows.push(["Biological Heart Age", `${data.heartAge || 45} yrs`, "Physiological estimation"]);
  clinicalRows.push(["Body Mass Index (BMI)", `${data.bmi || 22.4}`, `${data.bmiCategory || "Normal"} category`]);
  
  if (clinicalInputs.age !== undefined) {
    clinicalRows.push(["Chronological Age", `${clinicalInputs.age} yrs`, "Baseline demographic"]);
  }
  if (clinicalInputs.sex !== undefined) {
    clinicalRows.push(["Assigned Sex", clinicalInputs.sex === 1 ? "Male" : "Female", "Genetic marker"]);
  }
  if (clinicalInputs.trestbps !== undefined) {
    clinicalRows.push(["Resting Blood Pressure", `${clinicalInputs.trestbps} mm Hg`, "Systolic indicator"]);
  }
  if (clinicalInputs.chol !== undefined) {
    clinicalRows.push(["Serum Cholesterol", `${clinicalInputs.chol} mg/dl`, "Lipid profile parameter"]);
  }
  if (clinicalInputs.fbs !== undefined) {
    clinicalRows.push(["Fasting Blood Sugar", clinicalInputs.fbs === 1 ? "> 120 mg/dl" : "<= 120 mg/dl", "Metabolic status"]);
  }
  if (clinicalInputs.thalach !== undefined) {
    clinicalRows.push(["Maximum Heart Rate", `${clinicalInputs.thalach} bpm`, "Cardiovascular peak"]);
  }
  if (clinicalInputs.smoking !== undefined) {
    clinicalRows.push(["Smoking status", clinicalInputs.smoking === 2 ? "Frequent" : clinicalInputs.smoking === 1 ? "Occasional" : "Non-smoker", "Vascular factor"]);
  }
  if (clinicalInputs.stress_level !== undefined) {
    clinicalRows.push(["Neuro-Stress Level", clinicalInputs.stress_level === 2 ? "High" : clinicalInputs.stress_level === 1 ? "Medium" : "Low", "Endocrine factor"]);
  }
  
  autoTable(doc, {
    startY: 32,
    head: [["Biomarker Parameter", "Input Value", "Clinical Significance"]],
    body: clinicalRows,
    theme: 'grid',
    headStyles: { fillColor: [15, 23, 42] }, // slate-900
    margin: { left: 18, right: 15 },
    styles: { fontSize: 9 }
  });
  
  let finalY = doc.lastAutoTable.finalY || 100;
  
  // AI diagnostic explanation box
  doc.setFont("helvetica", "bold");
  doc.setFontSize(11);
  doc.setTextColor(15, 23, 42);
  doc.text("AI DIAGNOSTIC EXPLANATION SUMMARY", 18, finalY + 12);
  
  doc.setDrawColor(226, 232, 240);
  doc.line(18, finalY + 15, 195, finalY + 15);
  
  doc.setFont("helvetica", "normal");
  doc.setFontSize(9);
  doc.setTextColor(51, 65, 85);
  
  const explanationLines = doc.splitTextToSize(data.explanation || "No explanation details provided.", 175);
  doc.text(explanationLines, 18, finalY + 21);
  
  finalY += 21 + (explanationLines.length * 4.8);
  
  // Clinical recommendations box
  doc.setFont("helvetica", "bold");
  doc.setFontSize(11);
  doc.setTextColor(15, 23, 42);
  doc.text("CUSTOM CARDIOVASCULAR RECOMMENDATIONS", 18, finalY + 10);
  
  doc.line(18, finalY + 13, 195, finalY + 13);
  
  doc.setFont("helvetica", "normal");
  doc.setFontSize(9);
  doc.setTextColor(51, 65, 85);
  const recs = data.recommendations || [];
  let recsY = finalY + 19;
  recs.forEach((rec) => {
    const recLines = doc.splitTextToSize(`• ${rec}`, 175);
    doc.text(recLines, 18, recsY);
    recsY += recLines.length * 4.8;
  });
  
  // Cardiology Consultation Advisory & Disclaimer
  doc.setFillColor(254, 242, 242); // red-50
  doc.rect(18, 235, 177, 24, 'F');
  doc.setDrawColor(254, 202, 202); // red-200
  doc.setLineWidth(0.5);
  doc.rect(18, 235, 177, 24, 'S');
  
  doc.setFont("helvetica", "bold");
  doc.setFontSize(9);
  doc.setTextColor(220, 38, 38); // red-600
  doc.text("DOCTOR CONSULTATION ADVISORY:", 22, 242);
  
  doc.setFont("helvetica", "normal");
  doc.setFontSize(8);
  doc.setTextColor(127, 29, 29); // red-900
  const adviseText = doc.splitTextToSize("If your Risk Status is high or medium, please print this report and consult a cardiologist. Statistical indicators show risks that require validation from direct lab electrocardiograms and lipid profiles.", 169);
  doc.text(adviseText, 22, 247);
  
  // Disclaimer
  doc.setFont("helvetica", "normal");
  doc.setFontSize(7.5);
  doc.setTextColor(148, 163, 184);
  const disclaimerText = doc.splitTextToSize("Disclaimer: This assessment is generated utilizing machine learning models trained on patient groups. It constitutes a statistical estimation and does not represent an absolute clinical diagnostic review. Always consult medical experts for emergency treatment.", 177);
  doc.text(disclaimerText, 18, 268);
  
  // Footers
  doc.setFont("helvetica", "normal");
  doc.setFontSize(8.5);
  doc.setTextColor(100, 116, 139);
  doc.text("Generated by Heart Health Risk Assessment Tool", 18, 285);
  doc.text(`Timestamp: ${timestamp}  |  Page 2 of 2`, 135, 285);
  
  // Save PDF file
  const cleanedName = patientName.trim().replace(/\s+/g, '_') || 'Patient';
  const filename = `CardioSense_Report_${reportId}_${cleanedName}.pdf`;
  doc.save(filename);
};
